// align: "right",
// width: "100",
// prop: "test",
// label: "test",
// sortable: true,
// fixed: true,
// mini: true,
// format: true,
// json:true
let arr = [
    {
        width: "100",
        prop: "Title",
        sortable: true,
        fixed: true,
        mini: true,
    },
    {
        width: "190",
        prop: "Id",
        sortable: true,
        mini: true,
    },
    {
        width: "110",
        prop: "Surplusmoney",
        sortable: true,
        mini: true,
        label: "smoney",
        format: true,
        // json: true
    },
    {
        width: "110",
        prop: "Param.contact",
        sortable: true,
        label: "contact",
        mini: true,
        format: true,
    },
    {
        width: "100",
        prop: "Zonids",
        sortable: true,
        mini: true,
        format: true
    },
    {
        width: "90",
        prop: "Param.phone",
        sortable: true,
        mini: true,
        label: "phone",
        format: true,
    },
    {
        width: "130",
        prop: "Param.pricepublic",
        sortable: true,
        format: true,
        label: "pricepublic",
        mini: true,
    },
    {
        width: "130",
        prop: "Param.pricewaterpublic",
        sortable: true,
        format: true,
        label: "waterpublic",
        mini: true,
    },
    {
        width: "110",
        prop: "Param.paymode",
        sortable: true,
        format: true,
        label: "paymode",
        mini: true,
    },
    {
        width: "110",
        prop: "Param.balance",
        sortable: true,
        format: true,
        label: "balance",
        mini: true,
    },
    {
        width: "90",
        prop: "Param.area",
        sortable: true,
        label: "area",
        mini: true,
        format: true
    },
    {
        width: "100",
        prop: "Status",
        sortable: true,
        format: true,
        mini: true,
    },
]

module.exports = arr