// align: "right",
// width: "100",
// prop: "test",
// label: "test",
// sortable: true,
// fixed: true,
// mini: true,
// format: true,
// json:true
let arr = [
    {
        width: "130",
        prop: "Title",
        sortable: true,
        fixed: true,
        mini: true,
    },
    {
        width: "120",
        prop: "Zoneid",
        sortable: true,
        mini: true,
        format: true,
    },
    {
        width: "120",
        prop: "Uppermoduleid",
        sortable: true,
        label: "upmid",
        mini: true,
        format: true,
        // json: true
    },
    {
        width: "130",
        prop: "UpperPid",
        sortable: true,
        mini: true,
        format: true,
    },
    {
        width: "130",
        prop: "UpperPcode",
        sortable: true,
        label: "uppcode",
        mini: true,
        format: true,
    },
    {
        width: "90",
        prop: "Sharetype",
        sortable: true,
        label: "type",
        mini: true,
    },
    {
        width: "90",
        prop: "Sharerole",
        label: "role",
        sortable: true,
        mini: true,
    },
    {
        width: "130",
        prop: "Lowermoduleids",
        label: "lomids",
        sortable: true,
        mini: true,
        format: true,
    },
    {
        width: "130",
        prop: "LowerPids",
        sortable: true,
        label: "lopids",
        mini: true,
        format: true,
    },
    {
        width: "130",
        prop: "LowerPcodes",
        sortable: true,
        mini: true,
        label: "lopcodes",
        format: true,
    },
    {
        width: "130",
        prop: "LowerModules",
        sortable: true,
        label: "lomodules",
        mini: true,
        format: true
    },
    {
        width: "110",
        prop: "Id",
        sortable: true,
        mini: true,
        format: true,
    },
    {
        width: "110",
        prop: "Dividetype",
        sortable: true,
        label: "dtype",
        mini: true,
        format: true,
    },
    {
        width: "110",
        prop: "Apportionmoduleids",
        sortable: true,
        mini: true,
        label: "appmids",
        format: true,
    },
    {
        width: "110",
        prop: "ApportionPids",
        sortable: true,
        mini: true,
        label: "apppids",
        format: true,
    },
    {
        width: "130",
        prop: "ApportionPcodes",
        sortable: true,
        mini: true,
        label: "apppcodes",
        format: true,
    },
    {
        width: "130",
        prop: "ApportionModules",
        sortable: true,
        label: "appmodules",
        mini: true,
        format: true,
    }
]

export default arr